const styles = {
  container: {
    padding: '20px',
    fontFamily: 'Arial, sans-serif',
    display: 'flex',
    flexDirection: 'column',
    margin: '0 auto',    
    width: '100%',
    backgroundColor: '#f9f9f9',
    height: '100%',
    alignItems: 'center',
  },
  loader: {
    textAlign: 'center',
    marginTop: '50px',
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    marginBottom: '20px',
  },
  actions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '10px',
    marginTop: '10px',
    alignItems: 'center',
  },
  searchInput: {
    padding: '8px',
    fontSize: '14px',
    flex: '1 0 200px',
  },
  button: {
    padding: '8px 12px',
    cursor: 'pointer',
  },
  addButton: {
    padding: '8px 12px',
    backgroundColor: '#4CAF50',
    color: '#fff',
    border: 'none',
    cursor: 'pointer',
  },
  logoutButton: {
    padding: '8px 12px',
    backgroundColor: '#f44336',
    color: '#fff',
    border: 'none',
    cursor: 'pointer',
  },
  listContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    width: '100%',
  },
  cardContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '15px',
    width: '100%',
    justifyContent: 'center',
    paddingBottom: '20px',
  },
  listItem: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '10px',
    border: '1px solid #ddd',
    borderRadius: '6px',
    alignItems: 'center',
  },
  cardItem: {
    width: '200px',
    padding: '10px',
    border: '1px solid #ddd',
    borderRadius: '6px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  userActions: {
    display: 'flex',
    gap: '5px',
    marginTop: '5px',
  },
  smallButton: {
    padding: '5px 8px',
    cursor: 'pointer',
    fontSize: '12px',
  },
  pagination: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '10px',
    marginTop: '20px',
  },
  pageButton: {
    padding: '5px 10px',
    cursor: 'pointer',
  },
  modalBackdrop: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modal: {
    backgroundColor: '#fff',
    padding: '20px',
    borderRadius: '8px',
    width: '400px',
    maxWidth: '90%',
  },
  navbar: {
    width: "90%",
    height: "64px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 24px",
    marginBottom: "20px",
  },
  title: {
    fontSize: "20px",
    fontWeight: "600",
  },
  navActions: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  searchInput: {
    padding: "6px 10px",
    borderRadius: "4px",
    border: "1px solid #ccc",
    fontSize: "14px",
  },
  button: {
    padding: "6px 12px",
    border: "none",
    borderRadius: "4px",
    backgroundColor: "#2196f3",
    color: "#fff",
    fontSize: "14px",
    cursor: "pointer",
  },
  addButton: {
    padding: "6px 14px",
    border: "none",
    borderRadius: "4px",
    backgroundColor: "#4caf50",
    color: "#fff",
    fontSize: "14px",
    cursor: "pointer",
  },
  userSection: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginLeft: "16px",
  },
  username: {
    fontSize: "14px",
    fontWeight: "500",
  },
  avatar: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    backgroundColor: "#f44336",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
    fontSize: "16px",
    color: "#fff",
  },
  userInfo:{
    width: '80%',
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottom: '1px solid #ddd',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    backgroundColor: '#fff',
  }
};


export default styles;